[[repos]]
repo = "local"
hooks = [
  { id = "biome", name = "Biome lint & format", language = "system", entry = "bunx biome check --write --no-errors-on-unmatched --files-ignore-unknown=true", types_or = ["ts", "tsx", "json"], pass_filenames = true },
  { id = "typecheck", name = "TypeScript type check", language = "system", entry = "bunx tsc --noEmit", always_run = true, pass_filenames = false },
  { id = "schema-check", name = "Check JSON Schema is up to date", language = "system", entry = "bun run schema", always_run = true, pass_filenames = false }
]
